export const LOAD_BRAINFUCK_SUCCESS = 'LOAD_BRAINFUCK_SUCCESS';
export const LOAD_BRAINFUCK_FAILURE = 'LOAD_BRAINFUCK_FAILURE';
export const LOAD_STEP_SUCCESS = 'LOAD_STEP_SUCCESS';
export const STEP_INTERVAL_STARTED = 'STEP_INTERVAL_STARTED';

export const UPDATE_INPUT_SCRIPT = 'UPDATE_INPUT_SCRIPT';
